-- H2 DDL for SCA Ledger (signed splits + explicit CoA + funds)
-- Notes:
-- * Use Flyway migrations (this file is placed as V1__init.sql)
-- * Amounts are DECIMAL(19,4) for money; store signed per your convention.
-- * Disable hard deletes: use is_active + effective_from/effective_to where applicable.

CREATE TABLE chart_of_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  version VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL, -- DRAFT/ACTIVE/RETIRED
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chart_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(200) NOT NULL,
  account_type VARCHAR(20) NOT NULL, -- ASSET/LIABILITY/EQUITY/INCOME/EXPENSE
  normal_balance VARCHAR(10) NOT NULL, -- DEBIT/CREDIT
  parent_id BIGINT NULL,
  is_posting BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  effective_from DATE NULL,
  effective_to DATE NULL,
  description CLOB NULL,
  CONSTRAINT uq_account_code UNIQUE (chart_id, code),
  CONSTRAINT fk_account_chart FOREIGN KEY (chart_id) REFERENCES chart_of_accounts(id),
  CONSTRAINT fk_account_parent FOREIGN KEY (parent_id) REFERENCES account(id)
);

CREATE INDEX ix_account_parent ON account(parent_id);
CREATE INDEX ix_account_active ON account(is_active);

CREATE TABLE account_alias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  alias_text VARCHAR(400) NOT NULL,
  source VARCHAR(80) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_account_alias_account FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE INDEX ix_account_alias_account ON account_alias(account_id);
CREATE INDEX ix_account_alias_text ON account_alias(alias_text);

CREATE TABLE report_section (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  report_type VARCHAR(40) NOT NULL, -- INCOME_STATEMENT/BALANCE_SHEET/SCHEDULE/CUSTOM
  sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE account_report_section (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  report_section_id BIGINT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  sign_policy VARCHAR(20) NOT NULL DEFAULT 'NORMAL', -- NORMAL/INVERT
  CONSTRAINT uq_account_report UNIQUE (account_id, report_section_id),
  CONSTRAINT fk_ars_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_ars_section FOREIGN KEY (report_section_id) REFERENCES report_section(id)
);

CREATE INDEX ix_ars_account ON account_report_section(account_id);
CREATE INDEX ix_ars_section ON account_report_section(report_section_id);

CREATE TABLE schedule_kind (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE, -- RECEIVABLE/PREPAID/DEPOSIT/DEFERRED_REVENUE/PAYABLE/...
  name VARCHAR(200) NOT NULL
);

CREATE TABLE account_schedule_requirement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  schedule_kind_id BIGINT NOT NULL,
  is_required BOOLEAN NOT NULL DEFAULT TRUE,
  notes VARCHAR(500) NULL,
  CONSTRAINT uq_asr UNIQUE (account_id, schedule_kind_id),
  CONSTRAINT fk_asr_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_asr_kind FOREIGN KEY (schedule_kind_id) REFERENCES schedule_kind(id)
);

CREATE TABLE fund (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  fund_type VARCHAR(30) NOT NULL, -- UNRESTRICTED/TEMP_RESTRICTED/PERM_RESTRICTED/DESIGNATED/EVENT/OTHER
  parent_id BIGINT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  effective_from DATE NULL,
  effective_to DATE NULL,
  restriction_text CLOB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fund_parent FOREIGN KEY (parent_id) REFERENCES fund(id)
);

CREATE INDEX ix_fund_parent ON fund(parent_id);
CREATE INDEX ix_fund_active ON fund(is_active);

CREATE TABLE fund_alias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fund_id BIGINT NOT NULL,
  alias_text VARCHAR(400) NOT NULL,
  source VARCHAR(80) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_fund_alias_fund FOREIGN KEY (fund_id) REFERENCES fund(id)
);

CREATE INDEX ix_fund_alias_fund ON fund_alias(fund_id);
CREATE INDEX ix_fund_alias_text ON fund_alias(alias_text);

CREATE TABLE counterparty (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(200) NOT NULL,
  kind VARCHAR(20) NOT NULL, -- PERSON/ORG/OTHER
  email VARCHAR(200) NULL,
  phone VARCHAR(40) NULL,
  notes CLOB NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX ix_counterparty_name ON counterparty(display_name);

CREATE TABLE merchant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL UNIQUE,
  notes CLOB NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Transaction header
CREATE TABLE txn (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_date DATE NOT NULL,
  payee_id BIGINT NULL,
  memo VARCHAR(500) NULL,
  bank_account_id BIGINT NULL, -- points to an Account (asset) representing the bank register
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_txn_payee FOREIGN KEY (payee_id) REFERENCES counterparty(id),
  CONSTRAINT fk_txn_bank_account FOREIGN KEY (bank_account_id) REFERENCES account(id)
);

CREATE INDEX ix_txn_date ON txn(txn_date);
CREATE INDEX ix_txn_payee ON txn(payee_id);

-- Transaction splits (signed amounts, with fund as a required dimension)
CREATE TABLE txn_split (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  fund_id BIGINT NOT NULL,
  activity_id BIGINT NULL,
  merchant_id BIGINT NULL,
  nmr_flag BOOLEAN NOT NULL DEFAULT FALSE,
  notes VARCHAR(500) NULL,
  amount_signed DECIMAL(19,4) NOT NULL,
  CONSTRAINT fk_split_txn FOREIGN KEY (txn_id) REFERENCES txn(id) ON DELETE CASCADE,
  CONSTRAINT fk_split_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_split_fund FOREIGN KEY (fund_id) REFERENCES fund(id),
  CONSTRAINT fk_split_activity FOREIGN KEY (activity_id) REFERENCES activity(id),
  CONSTRAINT fk_split_merchant FOREIGN KEY (merchant_id) REFERENCES merchant(id)
);

CREATE INDEX ix_split_txn ON txn_split(txn_id);
CREATE INDEX ix_split_account ON txn_split(account_id);
CREATE INDEX ix_split_fund ON txn_split(fund_id);
CREATE INDEX ix_split_activity ON txn_split(activity_id);

-- Fund transfer object (explicit record + link to the posted txn)
CREATE TABLE fund_transfer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_date DATE NOT NULL,
  from_fund_id BIGINT NOT NULL,
  to_fund_id BIGINT NOT NULL,
  amount DECIMAL(19,4) NOT NULL,
  memo VARCHAR(500) NULL,
  status VARCHAR(20) NOT NULL, -- DRAFT/POSTED/VOID
  posted_txn_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ft_from FOREIGN KEY (from_fund_id) REFERENCES fund(id),
  CONSTRAINT fk_ft_to FOREIGN KEY (to_fund_id) REFERENCES fund(id),
  CONSTRAINT fk_ft_posted_txn FOREIGN KEY (posted_txn_id) REFERENCES txn(id)
);

CREATE INDEX ix_ft_date ON fund_transfer(transfer_date);
CREATE INDEX ix_ft_posted ON fund_transfer(posted_txn_id);
