-- V2: add schedule_item + schedule_link tables (for future UI parity with spreadsheet schedules)
-- This migration is safe to apply even if you haven't wired the UI yet.

CREATE TABLE schedule_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind VARCHAR(40) NOT NULL,     -- OUTSTANDING/RECEIVABLE/PAYABLE/PREPAID/DEPOSIT/DEFERRED_REVENUE/INVENTORY/FIXED_ASSET/etc.
  status VARCHAR(20) NOT NULL,   -- OPEN/CLEARED/PARTIAL/VOID
  counterparty_id BIGINT NULL,
  description VARCHAR(500) NULL,
  reference VARCHAR(200) NULL,
  amount DECIMAL(19,4) NOT NULL,
  due_date DATE NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sched_counterparty FOREIGN KEY (counterparty_id) REFERENCES counterparty(id)
);

CREATE INDEX ix_sched_kind_status ON schedule_item(kind, status);
CREATE INDEX ix_sched_counterparty ON schedule_item(counterparty_id);

CREATE TABLE schedule_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_item_id BIGINT NOT NULL,
  origin_split_id BIGINT NULL,
  clearing_split_id BIGINT NULL,
  CONSTRAINT fk_sched_link_item FOREIGN KEY (schedule_item_id) REFERENCES schedule_item(id) ON DELETE CASCADE,
  CONSTRAINT fk_sched_link_origin FOREIGN KEY (origin_split_id) REFERENCES txn_split(id),
  CONSTRAINT fk_sched_link_clearing FOREIGN KEY (clearing_split_id) REFERENCES txn_split(id)
);

CREATE INDEX ix_sched_link_item ON schedule_link(schedule_item_id);
